SCRIPTS_FOLDER_NAME = "scripts"

TEST_NONE_STATUS = "TC_EXECUTION_NONE"
TEST_PASS = "TC_EXECUTION_PASSED"
TEST_FAIL = "TC_EXECUTION_FAILED"
SOURCE_FILES_PATH = "SourceFiles"
CPPCHECK_OP_FILE = "cppcheck.xml"

SEPERATOR = '-'*124